# Generated by Django 2.2.3 on 2019-07-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sample_file',
            field=models.FileField(blank=True, null=True, upload_to='File/%Y/%m/%D/'),
        ),
    ]
